apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:16.7.0-ce.0
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          command: ["/bin/sh", "-c", "echo \"letsencrypt['enable'] = false\" > /etc/gitlab/gitlab.rb && echo \"postgresql['enable'] = false\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['initial_root_password'] = 'LetMeIn9'\" >> /etc/gitlab/gitlab.rb && echo \"external_url 'http://192.168.0.10:80'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_adapter'] = 'postgresql'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_encoding'] = 'utf8'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_host'] = '192.168.0.10'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_port'] = '5432'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_username'] = 'gitlab'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_password'] = 'LetMeIn9'\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['db_database'] = 'gitlabhq_production'\" >> /etc/gitlab/gitlab.rb; /assets/wrapper"]
          resources:
            limits:
              memory: 8Gi
              cpu: 4
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: gitlab-etc
              mountPath: /etc/gitlab
      volumes:
        - name: gitlab-etc
          persistentVolumeClaim:
            claimName: gitlab-etc

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: gitlab-http
      protocol: TCP
      port: 80
    - name: gitlab-ssh
      protocol: TCP
      port: 22
