---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:16.8.1-ce.0
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          resources:
            limits:
              memory: 8Gi
              cpu: 4
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: gitlab-etc
              mountPath: /etc/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        options:
          - name: ndots
            value: "5"
      volumes:
        - name: gitlab-etc
          persistentVolumeClaim:
            claimName: gitlab-etc
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: gitlab-http
      protocol: TCP
      port: 80
    - name: gitlab-ssh
      protocol: TCP
      port: 22
