apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_PASSWORD
              value: LetMeIn9
            - name: POSTGRES_DB
              value: gitlabhq_production
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /docker-entrypoint-initdb.d/postgresql.conf
              subPath: postgresql.conf
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: config
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gitlab
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gitlab
data:
  postgresql.conf: |
    # Add your custom postgresql.conf configuration here
    #     # Example:
    #         max_connections = 100
    #             shared_buffers = 128MB
    #
    data_directory = '/postgres-data'
