apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:16.2.3-ce.0
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          command: ["/bin/sh", "-c", "echo \"letsencrypt['enable'] = false\" >> /etc/gitlab/gitlab.rb && echo \"gitlab_rails['initial_root_password'] = 'LetMeIn9'\" >> /etc/gitlab/gitlab.rb && echo \"external_url 'http://gitlab:80'\" >> /etc/gitlab/gitlab.rb; /assets/wrapper"]
          resources:
            limits:
              memory: 4Gi
              cpu: 4
            requests:
              memory: 2Gi
              cpu: 2

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: gitlab-http
      protocol: TCP
      port: 80
    - name: gitlab-ssh
      protocol: TCP
      port: 22
